### ISSUE TITLE
Repository contains publicly available 213 code

### ISSUE THREAD

**Issue by bprail** [sam1323123/Projects#1]
Please remove all 213 code or make the repository private.

**Comment by sam1323123** [comment]
Removed 213 code except for self-written 213 files.

**Comment by bprail** [comment]
Slide 22 of your first lecture in 18-213 stated cheating is "Posting your code on the internet, now or in the future"

**Comment by sam1323123** [comment]
Sorry. Is it ok to post only our self-written 213 code?

**Comment by bprail** [comment]
Your self-written 213 code is the most important to remove.  Stressed students will search online for "help" and might find your code.  If they use your code, then you are liable for their actions.

**Comment by sam1323123** [comment]
Ok. I'll remove as much as possible.
